#! /usr/bin/ruby
require 'timeout'

INTERVAL        = 10
STEP_DOWN_RATE          = 1.5
DEVICE_ID       = "en0"
NETWORK_SERVICE = "Wi-Fi"
VERBOSE         = false

def networksetup(flag)
  std_read, std_write = IO.pipe
  err_read, err_write = IO.pipe
  command = "networksetup -#{flag}"
  puts command if VERBOSE
  system(command, out: std_write, err: err_write)
  std_write.close
  err_write.close
  std_lines = std_read.readlines
  err_lines = err_read.readlines
  puts std_lines if VERBOSE
  return std_lines, err_lines
end

def network
  lines, errs = networksetup("getairportnetwork #{DEVICE_ID}")

  # You are not associated with an AirPort network.
  # Wi-Fi power is currently off.

  # Current Wi-Fi Network: Karma Wi-Fi
  lines.join('\n') =~ /Current Wi-Fi Network: (.+)$/i
  $1
end

def cycle_airport
  %w(off on).each do |state|
    networksetup("setairportpower - #{state}")
  end
end

begin
  Timeout::timeout(60) do
    wait_time = INTERVAL
    until network
      cycle_airport
      print '.'
      sleep wait_time
      wait_time *= STEP_DOWN_RATE
    end
  end
  puts "\nConnected to '#{network}'"
  exit 0
rescue Timeout::Error
  puts "\nUnable to connect to router"
  exit 1
end
